name: Deploy Meetings Manager

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get secret
        run: echo "$PKEY" > pkey.pem
        env: 
          PKEY: |
            ${{ secrets.PKEY }}

      - name: set secret permission
        run: sudo chmod 600 pkey.pem

      - name: transfer api
        run: sudo scp -i pkey.pem -o StrictHostKeychecking=no $PHOST:../Backend /home/ubuntu/
        env: 
          PHOST: ${{ secrets.PHOST }}

      - name: test key
        run: sudo ssh -i pkey.pem -o StrictHostKeychecking=no $PHOST 'touch test.txt && echo "working123" > test.txt'
        env: 
          PHOST: ${{ secrets.PHOST }}

#    - name: Checkout code
#      uses: actions/checkout@v2

#    - name: Install Flyway
#      run: sudo snap install flyway --classic

#    - name: Apply database migrations
#      run: cd flyway 
#           && ls 
#           && echo -e "\nflyway.password=12345678" >> flyway.conf
#           && echo -e "Running migrations!\n"
#           && flyway migrate
